CREATE DATABASE INFO_330_6AB
USE INFO_330_6AB

CREATE TABLE tblPRODUCT
(ProductID INT IDENTITY(1,1) primary key,
ProductName VARCHAR(30) NOT NULL,
ProductDEescription VARCHAR (100) NULL,
ProductPrice NUMERIC(8,2))
GO

CREATE TABLE tblORDER_PRODUCT
(OrderProductID INT IDENTITY(1,1) primary key,
SalesOrderID INT FOREIGN KEY REFERENCES tblSALES_ORDER (SalesOrderID) NOT NULL,
ProductID INT FOREIGN KEY REFERENCES tblPRODUCT (ProductID) NOT NULL,
OrderQuanntity VARCHAR(10) NOT NULL)
GO

CREATE TABLE tblSALES_ORDER
(SalesOrderID INT IDENTITY(1,1) primary key,
OrderDescription VARCHAR(100) NULL,
OrderDate DATE NOT NULL,
StoreID INT FOREIGN KEY REFERENCES tblSTORE (StoreID) NOT NULL,
DistributorID INT FOREIGN KEY REFERENCES tblDISTRIBUTOR (DistributorID) NOT NULL,
OrderAmount VARCHAR(10))
GO

CREATE TABLE tblREVIEW
(ReviewID INT IDENTITY(1,1) primary key,
ReviewDescr VARCHAR(100) NULL,
SalesOrderID INT FOREIGN KEY REFERENCES tblSALES_ORDER (SalesOrderID) NOT NULL)
GO

CREATE TABLE tblSTORE
(StoreID INT IDENTITY(1,1) primary key,
StoreName VARCHAR(30) NOT NULL)
GO

CREATE TABLE tblDISTRIBUTOR 
(DistributorID INT IDENTITY(1,1) primary key,
DistributorType VARCHAR(30) NOT NULL,
DistributorName VARCHAR(30) NOT NULL)
GO

CREATE TABLE tblPURCHASE_ORDER
(PurchaseOrderID INT IDENTITY(1,1) primary key,
FarmerID INT FOREIGN KEY REFERENCES tblFARMER (FarmerID) NOT NULL,
OrderDescription VARCHAR(100) NULL,
OrderAmount NUMERIC(8, 2) NOT NULL,
OrderDate DATE NOT NULL,
DistributorID INT FOREIGN KEY REFERENCES tblDISTRIBUTOR (DistributorID) NOT NULL)
GO

CREATE TABLE tblFARMER
(FarmerID INT IDENTITY(1,1) primary key,
FarmerFname VARCHAR(10) NOT NULL,
FarmerLname VARCHAR(30) NOT NULL)
GO